services:

  node-red:
    container_name: tasluf-node-red
    build:
      context: ./nodered-custom/
      dockerfile: Dockerfile
    image: tasluf_nodered:latest
    environment:
      - TZ=Europe/Amsterdam
      - MYSQLUSERNAME=root
      - MYSQLPASSWORD=example
    ports:
      - "1880:1880"
    networks:
      tasluf-network:
        ipv4_address: 172.40.0.100
    volumes:
      - ./nodered-custom/data:/data

  mosquitto:
    container_name: tasluf-mosquitto
    image: eclipse-mosquitto
    volumes:
    - ./mosquitto/config:/mosquitto/config
    - ./mosquitto/log:/mosquitto/log
    - ./mosquitto/data/:/mosquitto/data
    restart: always
    networks:
      tasluf-network:
        ipv4_address: 172.40.0.101
    ports:
    - "1883:1883" 

  db:
    image: mysql
    container_name: tasluf-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
    - "3306:3306" 
    volumes:
    - ./mysql-dump:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: tasluf-mysql-adminer
    restart: always
    ports:
      - "8080:8080"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: tasluf-rabbitmq
    ports:
      - "5672:5672"    # Port for RabbitMQ client connections
      - "15672:15672"  # Port for RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      tasluf-network:
        ipv4_address: 172.40.0.105

  influxdb:
    container_name: tasluf-influxdb
    image: influxdb:2.7.4
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin1234!
      - DOCKER_INFLUXDB_INIT_ORG=univaq
      - DOCKER_INFLUXDB_INIT_BUCKET=se4iot
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=Ga8nVsXP4FAe5_M1a5j7uCa4zO_u_M9oUsO8wUSWh_wPbR3clc9ZTv420Li9adOVCPl1tGvn6hLHfI5gP7Lm5A==
    networks:
      tasluf-network:
        ipv4_address: 172.40.0.104
    
  telegraf:
    image: telegraf:latest
    container_name: tasluf-telegraf
    environment:
        - INFLUX_TOKEN=gouxSHeT6vFosIziMftUDbTyUt153JPMICBq_A0Lt-_n3MdseeFUH9GDSQqeqY7_9b8bGvCOB2rFxHltB51_DQ==
    command: >
      telegraf --config /etc/telegraf/telegraf.conf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mosquitto
    restart: unless-stopped
    networks:
      - tasluf-network

  grafana:
    container_name: tasluf-grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000" # Expose Grafana on port 3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin # Grafana admin username
      - GF_SECURITY_ADMIN_PASSWORD=admin # Grafana admin password
    depends_on:
      - influxdb
    networks:
      tasluf-network:
        ipv4_address: 172.40.0.106
    volumes:
      - ./grafana/data:/var/lib/grafana # Persistent storage for Grafana


networks:
  tasluf-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/16